{''
 'name': 'Lease Management',
 'summary': """Custom for ERP""",
 'version': '0.1',
 'sequence':'-999999',
 'description': """Lease/Rental Management System""",
 'author': 'Ideenkreise Tech Pvt Ltd',
 'company': 'Ideenkreise Tech Pvt Ltd',
 'website': 'https://www.ideenkreisetech.com',
 'category': 'Tools',
  'depends': ['account','purchase','stock','product_purchase','base','dynamic_accounts_report'],
 'license': 'AGPL-3',
 'data': [

  'security/ir.model.access.csv',
  'security/group.xml',
  'views/stock_picking_inherit.xml',
   'views/deligate_user_po.xml',
   'views/chatter_hide.xml',
  'views/purchase_order_line_inherit.xml',
  'views/lms.xml',
  'views/po_workflow.xml',
  'views/masters.xml',
  'views/reports.xml',
  'data/sequence.xml',
  'data/cron.xml',
  'data/mail_template.xml',
  'wizard/confirm.xml',
  'wizard/lease_revert.xml',
  'wizard/vendor_mail.xml',
  'wizard/export_purchase_wizard_form.xml',
  'wizard/export_lease_wizard.xml',
  'wizard/assign_user.xml',
  'views/deligate_user_lease.xml',
  'views/lease_purchase.xml',
  'views/lease_invoice.xml',
  'views/po_list.xml',
  'views/tds.xml',
  'report/report.xml',
  'report/purchase_report.xml',
   'wizard/close_wizard.xml',
  

 ],
 'demo': ['demo/demo.xml'],
 'installable': True,
 'auto_install': False,
 'application' : True
 }
