{
    'name': 'Product Purchase',
    'version': '1.0.0',
    'category': 'Purchase products',
    'author': 'ideenkreise',
    'sequence': -100,
    'summary': 'purchase management system',
    'description': """product purchase management system""",
    'depends': ['base', 'account', 'hr', 'stock', 'purchase', 'base_accounting_kit', 'web_domain_field'],
    'data': [
        'views/delegate_user_admin.xml',
        'views/invoice_inherit.xml',
        'views/deligate_user_invoice.xml',
        'views/invoice_rfi.xml',
        'views/product_template_inherit.xml',
        'views/deligate_user_cr.xml',
        'views/deligate_user_cr_need.xml',
        'views/vendor_approval_view.xml',

        'views/product_tender_line.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/tenders.xml',

        'views/product_contracts.xml',


        # 'views/product_request_emp.xml',
        'views/product_request.xml',

        'views/expense_category.xml',
        'views/groups.xml',
        'data/sequence_data.xml',
        'data/cron.xml',
        'views/contract.xml',
        # 'wizard/add_to_bidding.xml',
        'wizard/assign_buyer.xml',
        'wizard/deadline_extend.xml',
        'wizard/add_approver_workflow.xml',
        
        'wizard/revert_back.xml',
        'wizard/revert_back_tender.xml',
        'wizard/vendor_selection.xml',
        'wizard/price_history.xml',
        'wizard/export_contract_wizard_form.xml',
        'wizard/pr_reject.xml',
        'wizard/purchase_wizard_status.xml',
        'wizard/add_branch.xml',
        'wizard/negotiation_comparison.xml',
        'wizard/po_branch.xml',

        'views/user_inherit.xml',
        'views/po_inherit.xml',
        'views/deligate_user.xml',
        'views/product_request_budget.xml',
        'views/pr_approve_users.xml',
        'report/report.xml',
        'report/contract_report.xml',
        'views/menu.xml',
        'views/contract_compare_line.xml',
        'views/purchase_status.xml',
        'views/contract_nego.xml',

    ],
    'demo': [],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'multi_company': True
}
